### PR TITLE
Add Custom hal example for PCA9685 PWM breakout board 

### PR DESCRIPTION
**Pull request by samjt**
This is an example for using a PWM extender board.

My c++ is pretty amateurish, so there are probably some things to change.

One issue is that the PCA board sets brightness across a higher resolution than jled (4096 levels instead of 256). I think this is the reason there is some flickering during fades, but I’m not sure how to correct it. At the moment I’m just doing `map(val, 0, 255, 0,4095)` in the analogWrite call.

### CODE REVIEW

**Comment by jandelgado** [comment]
Thanks for the contribution! However, in order to make an executable example, it still needs some polishing. Since I've a PCA9685 somewhere around, I can take care of that and take your work as a starting point. Also I would like to put the example in a separate repository, since it has additionals dependencies (the PCA9685 driver - which I don't want to add to JLed). See https://github.com/jandelgado/jled-example-switch-sequence for an example.

**Comment by samjt** [comment]
Sure, I thought that would be the case but I don’t think I can open a pr to start a new repo. Feel free to close

**Comment by jandelgado** [comment]
I have added a library new  with a PCA9685 HAL: https://github.com/jandelgado/jled-pca9685-hal/

See the repo for usage examples / documentation.

**Comment by samjt** [comment]
Amazing, and great detailed documentation, thank you.

**Pull request closed without merging**
